name: dbv_virtual
description: "Gerenciamento de clube de desbravadores"

version: 1.4.6+46

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  clipboard: ^0.1.3
  crop_image: ^1.0.13
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  email_validator: ^3.0.0
  extended_masked_text: ^3.0.1
  fast_cached_network_image: ^1.2.9
  file_picker: ^8.0.6
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter_dotenv: ^5.1.0
  flutter_gemini: ^2.0.4
  flutter_colorpicker: ^1.1.0
  html: ^0.15.4
  http: ^1.2.1
  image_compression_flutter: ^1.0.4
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.5.0
  intl: ^0.19.0
  network_to_file_image: ^6.0.1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  pdf: ^3.11.0
  pdf_compressor: ^0.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  syncfusion_flutter_calendar: ^26.2.9
  syncfusion_flutter_charts: ^26.2.9
  syncfusion_flutter_datagrid: ^26.2.5
  syncfusion_flutter_pdfviewer: ^26.1.41
  url_launcher: ^6.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

#flutter_launcher_icons:
#  windows:
#    generate: true
#    image_path: "assets/images/clube_logo.png"
#    icon_size: 256 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/files/
    - assets/images/

  fonts:
    - family: Bkdbd
      fonts:
        - asset: assets/fonts/Bkdbd.ttf